FROM alpine
RUN apk add --no-cache curl wget busybox-extras netcat-openbsd python py-pip && \
    pip install awscli
RUN apk --purge -v del py-pip
RUN apk add bash
RUN apk add htop
CMD tail -f /dev/null

